# Generated by Django 5.0.6 on 2024-06-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic_app', '0002_officedetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Register',
        ),
    ]
