# Generated by Django 5.0.6 on 2024-06-07 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic_app', '0003_rename_users_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officedetail',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='logic_app.userdetail'),
        ),
    ]
